# Generated by Django 5.2 on 2025-05-03 07:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0002_dweets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dweets',
            new_name='Dweet',
        ),
    ]
